# Generated by Django 5.2.9 on 2025-12-30 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст вопроса (RU)')),
                ('text_uk', models.TextField(blank=True, null=True, verbose_name='Текст вопроса (UK)')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Текст вопроса (EN)')),
                ('text_fr', models.TextField(blank=True, null=True, verbose_name='Текст вопроса (FR)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lessons_app.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'lessons_question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст ответа (RU)')),
                ('text_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст ответа (UK)')),
                ('text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст ответа (EN)')),
                ('text_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст ответа (FR)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Это правильный ответ?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizzes.question')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'db_table': 'lessons_choice',
            },
        ),
    ]
