# Generated by Django 5.2.9 on 2026-01-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст ответа'),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вопроса'),
        ),
    ]
