# Generated by Django 4.1.7 on 2025-11-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок и эмодзи (напр., Урок 1: 🇫🇷 Фонетика)')),
                ('data_lesson_id', models.CharField(max_length=20, unique=True, verbose_name='ID урока (lesson1, lesson2...)')),
                ('content_html', models.TextField(verbose_name='HTML-содержимое урока (с тегами H3, P, UL и т.д.)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['order'],
            },
        ),
    ]
