# Generated by Django 5.2.9 on 2025-12-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_html_en',
            field=models.TextField(blank=True, null=True, verbose_name='Контент (EN)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_html_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Контент (FR)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_html_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Контент (RU)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_html_ua',
            field=models.TextField(blank=True, null=True, verbose_name='Контент (UA)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (FR)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_ua',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (UA)'),
        ),
    ]
