# Generated by Django 5.2.9 on 2025-12-20 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_content_html_en_lesson_content_html_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст вопроса (RU)')),
                ('text_ua', models.TextField(blank=True, null=True, verbose_name='Текст вопроса (UA)')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Текст вопроса (EN)')),
                ('text_fr', models.TextField(blank=True, null=True, verbose_name='Текст вопроса (FR)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст ответа (RU)')),
                ('text_ua', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст ответа (UA)')),
                ('text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст ответа (EN)')),
                ('text_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст ответа (FR)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Это правильный ответ?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='lessons.question')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
    ]
