# Generated by Django 5.2.9 on 2025-12-20 22:58

import django_ckeditor_5.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_question_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content_html',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='HTML-содержимое урока (с тегами H3, P, UL и т.д.)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_html_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент (EN)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_html_fr',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент (FR)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_html_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент (RU)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_html_ua',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент (UA)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lessons.lesson', verbose_name='Урок'),
        ),
    ]
