# Generated by Django 5.2.9 on 2025-12-29 20:16

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (RU)')),
                ('title_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (UK)')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (EN)')),
                ('title_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (FR)')),
                ('content_html_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент (RU)')),
                ('content_html_uk', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент (UK)')),
                ('content_html_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент (EN)')),
                ('content_html_fr', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент (FR)')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок и эмодзи (напр., Урок 1: 🇫🇷 Фонетика)')),
                ('data_lesson_id', models.CharField(max_length=20, unique=True, verbose_name='ID урока (lesson1, lesson2...)')),
                ('content_html', django_ckeditor_5.fields.CKEditor5Field(verbose_name='HTML-содержимое урока (с тегами H3, P, UL и т.д.)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'db_table': 'lessons_lesson',
                'ordering': ['order'],
            },
        ),
    ]
