# Generated by Django 5.2.9 on 2026-01-09 03:34

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content_html_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='HTML-содержимое урока (с тегами H3, P, UL и т.д.)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_html_fr',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='HTML-содержимое урока (с тегами H3, P, UL и т.д.)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_html_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='HTML-содержимое урока (с тегами H3, P, UL и т.д.)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_html_uk',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='HTML-содержимое урока (с тегами H3, P, UL и т.д.)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок и эмодзи (напр., Урок 1: 🇫🇷 Фонетика)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок и эмодзи (напр., Урок 1: 🇫🇷 Фонетика)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок и эмодзи (напр., Урок 1: 🇫🇷 Фонетика)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок и эмодзи (напр., Урок 1: 🇫🇷 Фонетика)'),
        ),
    ]
