# Generated by Django 5.2.9 on 2026-08-23 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_app', '0002_alter_lesson_content_html_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название темы')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Название темы')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название темы')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название темы')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='Название темы')),
                ('emoji', models.CharField(default='📁', max_length=10, verbose_name='Эмодзи / Иконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Тема / Модуль',
                'verbose_name_plural': 'Темы / Модули',
                'db_table': 'lessons_topic',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='lessons_app.topic', verbose_name='Тема / Модуль'),
        ),
    ]
